# Generated by Django 5.2.4 on 2026-07-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_drink_stock_alter_drink_price_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='min_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
