# Generated by Django 5.2.4 on 2025-12-06 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_depense_options_alter_drink_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÖØ-öø-ÿ]{1,10}$', message='Le nom doit être un seul mot (lettres seulement) et maximum 10 caractères.')])),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='depense',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personne'),
        ),
    ]
