# Generated by Django 5.2.4 on 2026-06-09 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÖØ-öø-ÿ]{1,10}$', message='Le nom doit être un seul mot (lettres seulement) et maximum 10 caractères.')])),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['name'],
            },
        ),
    ]
