# Generated by Django 5.2.4 on 2025-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_depense_drink_prix_achat_drink_prix_vente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
